output "id" {
  value       = azurerm_linux_function_app.this.id
  description = "Azure Functions ID"
}

output "application_url" {
  value       = "https://${azurerm_linux_function_app.this.name}.azurewebsites.net"
  description = "Azure Functions application URL"
}

# output "application_caf_name" {
#   value       = azurecaf_name.function_app.result
#   description = "The application name generated by the Azure Cloud Adoption Framework."
# }
