name: Continuous Delivery

on:
  push:
  pull_request:
    types: [ closed ]

jobs:
  run-unit-tests:
    name: CI - Run Unit Tests
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        working-directory: ./src
        run: |
          mkdir -p test_results
          docker build . --target unit-tests-runner --tag ticketless-flow-app-unit-tests:latest
          docker run --volume $(pwd)/test_results:test_results ticketless-flow-app-unit-tests:latest
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Dotnet test results
          path: "src/test_results/*.trx"
          reporter: dotnet-trx
          fail-on-error: true

  # run-integration-tests:
  #   name: CI - Run Integration Tests
  #   runs-on: ubuntu-latest
  #   # runs-on: self-hosted
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Run Integration Tests
  #     working-directory: ./src
  #     run: |
  #       docker build . --target integration-tests-runner --tag ticketless-flow-app-integration-tests:latest
  #       docker run ticketless-flow-app-integration-tests:latest

  docker-push:
    name: CI - Build and push Docker image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - run-unit-tests
      # - run-integration-tests
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: ./src
        run: docker build . --build-arg REPOSITORY_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" --tag ticketless-flow-app:$(date +%s) --tag ticketless-flow-app:latest
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Push Docker image
        run: |
          docker tag ticketless-flow-app:latest ghcr.io/dev-experience/ticketless-flow-app:latest
          docker push ghcr.io/dev-experience/ticketless-flow-app:latest
      - name: Inspect Docker image
        run: docker inspect ghcr.io/dev-experience/ticketless-flow-app:latest
