name: Continuous Delivery

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build-docker-image:
    name: CI - Build Docker image
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./src/TicketlessFlowApp
      run: docker build . --file Dockerfile --tag ticketless-flow-app:$(date +%s)
