name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: echo $(date +%s)
    - run: pwd
    - run: ls -a
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ticketless-flow-app:$(date +%s)
